//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualPerception.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experiment5Result
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public string ProvidedIncentive { get; set; }
        public string ReproducedIncentive { get; set; }
        public int NumberReproducedOfIncentive { get; set; }
        public int NumberGroupsWithWord { get; set; }
        public double RelativeDistributionWord { get; set; }
        public int NumberGroupsHallmark { get; set; }
        public string Hallmark { get; set; }
        public int NumberDisplay { get; set; }
        public int AllNumberDisplay { get; set; }
    
        public virtual User User { get; set; }
    }
}
